### PR TITLE
Added draft 1 of jhm

### PR DESCRIPTION
**Pull request by garethahealy**
https://github.com/DozerMapper/dozer/issues/94

### CODE REVIEW

**Comment by garethahealy** [comment]
This PR provides the foundations for using JHM. Further tests need to be defined, currently, i think the following should be added:

- Different type mapping
- Deep mapping
- Collection mapping
- Mappings without XML

**Comment by garethahealy** [comment]
@orange-buffalo @buzdin ; ideas for other tests to add?

**Comment by buzdin** [comment]
Comments:
* Mappings with annotations, API and XML should not differ, because everything is processed in one core. No point on making a special test case imo.
* Generic collections is a special case.
* Polymorphic mapping based on interface has special treatment and might be slow.
* Array mapping
* Deeply nested objects, say 7 levels of properties.

**Comment by garethahealy** [comment]
I am going to merge this, as it gives the foundation, which needs to be expanded upon. Further PRs need to be raised as per:
- https://github.com/DozerMapper/dozer/pull/431#issuecomment-308235977

**Pull request merged**
