### PR TITLE
fix for issues #242 and #244

### PR DESCRIPTION
**Pull request by ZuperKeurZ**
Fix for issue #242
Fix for issue #244

### CODE REVIEW

**Comment by lauriharpf** [comment]
Hi @ZuperKeurZ! Appreciate the pull request and the bug reports. Unfortunately, I have not had the chance to look into this issue and the pull request yet.

There seem to be some test failures on the CI server related to the pull request. Do you have the opportunity to fix them? 

    Failed tests:   testBeanMappingBuilder(org.dozer.spring.functional_tests.SpringIntegrationTest): expected:<John> but was:<null>
      testInjectConverter(org.dozer.spring.functional_tests.SpringIntegrationTest): expected:<1> but was:<0>

**Comment by garethahealy** [comment]
@ZuperKeurZ ; can you rebase with latest to force travis to retest

**Comment by garethahealy** [comment]
@ZuperKeurZ ; any update?

**Comment by garethahealy** [comment]
Closing due to inactivity.

**Pull request closed without merging**
