### PR TITLE
fixes #287

### LINKED ISSUE #287: All types of Collection are handled as List
see `MappingProcessor`

```
577 if (destCollectionType.getName().equals(Collection.class.getName())){
578          destCollectionType = List.class;
579 }
```

At least a `java.util.Set` should be supported. I've already sent a PR but didn't open an issue so far.
https://github.com/DozerMapper/dozer/pull/267

### PR DESCRIPTION
**Pull request by openwms**
At least consider implementations of java.util.Set and do not map any Collection to Lists! ... to be extended

### CODE REVIEW

**Comment by openwms** [comment]
improves handling of Set ... https://github.com/DozerMapper/dozer/issues/172

**Comment by garethahealy** [comment]
@openwms ; can you rebase on latest please and add a unit test.

**Comment by garethahealy** [comment]
@openwms ; Have you finished the rebase? as it doesn't seem correct. I wouldn't expect to see all the commits from the past few weeks. Only your commits.

**Comment by openwms** [comment]
@garethahealy Have added a unit test for this

**Pull request merged**
