### PR TITLE
Updated osgi imports to not import the exports

### PR DESCRIPTION
**Pull request by garethahealy**
https://github.com/DozerMapper/dozer/issues/512

CC @orange-buffalo

### CODE REVIEW

**Comment by garethahealy** [comment]
@orange-buffalo ; for javassist, that would be OK, but for hibernate it would generate a version range of: 4.2,5, which would exclude latest.

**Comment by orange-buffalo** [comment]
Indeed, default BND versioning scheme works this way. There is a configuration to override this (http://bnd.bndtools.org/chapters/170-versioning.html, section 10.8), but it will have effect for all imports, not sure if it can be specified for a single package. 

But I believe we still can make changes in  a way that avoids double-maintenance of version numbers if instead of 
```
org.hibernate.proxy;version="[4.2,6)";resolution:=optional,
```
we have
```
org.hibernate.proxy;version="[${hibernate-core.version})";resolution:=optional,
```
Of course, to apply this we should specify the minimum version of Hibernate dependency we need.

PS. This is just a suggestion, I do not insist on making changes here.

**Comment by garethahealy** [comment]
Did you mean, i.e.: we provide minimum and current version:
`org.hibernate.proxy;version="[4.2,${hibernate-core.version})";resolution:=optional,`

As if we just did:
`org.hibernate.proxy;version="[${hibernate-core.version})";resolution:=optional,`

Isnt that the same as now?

**Comment by orange-buffalo** [comment]
I see two aspects here. 

First is that we have Hibernate dependency version defined in the project as `5.2.10.Final`, although we need only one interface which is available since much earlier version (4.2?). In my view, we should keep project dependency at the minimum required version and then it can be used as a left inclusive range end (either by bundle plugin or via manual configuration using maven property). 

Second thing is that for OSGi we basically need "unbound" version range, i.e. starting from the minimum required and with no right end. I found that this is supported by some providers (like [here](http://www.eclipse.org/virgo/documentation/virgo-documentation-3.7.0.M01/docs/virgo-user-guide/html/ch02s02.html)). Not sure what spec says about unbound range and if this semantic is supported by other vendors. 
If it is commonly supported, we could use (assuming our project dependency version is downgraded):
```
org.hibernate.proxy;version="${hibernate-core.version}";resolution:=optional,
```
If not, than we should set the left end to our minimum required version, and the right end to some future major version (it is quite hard to say what will come with [Hibernate 6 and 7](https://github.com/hibernate/hibernate-orm/wiki/Roadmap), but for the time being we could assume they will not break proxy interface):
```
org.hibernate.proxy;version="[${hibernate-core.version},8)";resolution:=optional,
```

**Comment by garethahealy** [comment]
For time being, have commented out versions to be non-opinionated as theres no clean way to support this currently. will revisit.

**Pull request merged**
