### PR TITLE
fix: refactor certain methods in ClassMapBuilder.java

### PR DESCRIPTION
**Pull request by Umang-20**
## Issue link

        [ISSUE: 101] [My First PR](fix: refactor certain methods in ClassMapBuilder.java)

## Purpose
ClassMapBuilder has a method called apply that contains many operation in a single method. And certain block level variable names are not self explanatory.

## Approach
So, I refactor that method into smaller methods in one responsibility using Extract method. And also gave self-explanatory variable names to certain variables.

### CODE REVIEW

**Comment by Umang-20** [comment]
@garethahealy, Can you check this PR?

**Comment by garethahealy** [comment]
@Umang-20 ; is this fixing a bug or code tidy-up?, if it's code tidy (_based on PR name and description_), I'd rather not accept. 

The project is inactive, so accepting a code change that doesn't fix an issue but potentially introduces an issue by mistake is high risk.
- https://github.com/DozerMapper/dozer#project-activity

**Comment by Umang-20** [comment]
@garethahealy, This PR is for code-refactoring. I am master's student and have got an assignment to raise PR to a legacy project making this changes. So my assignment marks are dependent on it.

**Comment by Umang-20** [comment]
So, if possible can you merge this into some another branch?

**Comment by Umang-20** [comment]
@garethahealy, I have changed base branch for PR. As I saw that you have created new branch for me.

**Comment by Umang-20** [comment]
@garethahealy, If it’s possible can you please merge this today. I have my deadline for assignment today.

**Comment by Umang-20** [comment]
Thanks @garethahealy, for merging this PR.

**Pull request merged**
