### PR TITLE
Patch for #104

### PR DESCRIPTION
**Pull request by josebarragan**
Converting JAXBElement objects to Plain Old Java Types
New JAXBElementConverter to support JAXB full processing

### CODE REVIEW

**Comment by josebarragan** [comment]
Hi Lauri,

What is the progress state of merging this pull-request?
It's becoming too old, don't you think? 
It's absolutely tested in our production projects for more than 2 years, what's the problem with?

Thanks!

**Comment by lauriharpf** [comment]
Hi @josebarragan. The only problem has been my lack of time to look into this, as I would like to understand what I merge and why.

You are absolutely right to point out that this has taken much too long. I will set aside some time next week to read through the issue, the code and do the merge.

**Comment by josebarragan** [comment]
Thanks in advance @lauriharpf

**Comment by lauriharpf** [comment]
@josebarragan, I have went through the pull request. Correct me if I am mistaken, but it appears to fix several JAXB-related mapping problems:

* From a JAXBElement<Foo> field in POJO A to a Foo field in POJO B
* From (e.g.) a String field in POJO A to a JAXBElement<String> field in POJO B
* Directly from an instance of Foo to an instance of JAXBElement<Foo>
* Plus some degree of Calendar-to-String mapping

## Questions
All in all, this looks like a really nice pull request and OK to merge. However, you might be able to clarify some things that are a bit unclear to me. No need to fret about changing anything before the merge unless you want to - I would just like your opinions on the following:

### JAXBElementConverter

#### Convert method
The convert method finds the correct create method from the ObjectFactory. Convert changes the destination class to match the parameter type in the create method. This seems necessary e.g. when mapping XMLGregorianCalendars. I don't understand this, though:

    Class<?>[] paramTypes = {destClass};
    method = ReflectionUtils.getMethod(factoryClass, methodName, paramTypes);

Why re-search for the method? Removing this part does not break any tests, but is there something I am missing?

#### Searching for the create method
Since it gets repeated in getBeanId and convert, how would you feel about extracting this to a small helper method? I dumped a [draft to PasteBin](http://pastebin.com/kB0rDEws) to illustrate. 

### XMLGregorianCalendarConverter
You tend to fully qualify class names and use the cast() method instead of the operator. Just a matter of preference or are there underlying reasons for it?

I am tempted to change 

     if (java.util.Date.class.isAssignableFrom(sourceClass)) {
         // Date --> XMLGregorianCalendar
         result.setTime(java.util.Date.class.cast(srcObj));
     }

to 

    if (Date.class.isAssignableFrom(sourceClass)) {
        // Date --> XMLGregorianCalendar
        result.setTime((Date)srcObj);
    }

and do the same in other similar situations (in this class and in e.g. MappingProcessor). The latter form is more readable to me.

*Thanks for the pull request and for your patience!*

**Comment by josebarragan** [comment]
Hi @lauriharpf 

After review your proposal of change on the JAXBElementConverter class, I think you have a good point.  The original motivation was, granted to get the real method implementation based on real parameters, but it doesn’t really happen at the end, ergo your proposal seems OK for me.

Regarding the use of Object.class.cast(d) instead of (Object)d, is a criteria that I use, in order to use the new java 6 API for this.

Hope I’ve clarified your doubts about it.
Thanks for your effort and patience.

We keep in touch.

**Comment by brunolellis** [comment]
Hi,
It doesn't seem that this PR is available on maven (version 5.5.1). Am I correct? 
Is it possible to release a new version regarding this feature, please?

**Comment by brunolellis** [comment]
Just saw that #101 is going to be released in the next version (5.5.2): https://github.com/DozerMapper/dozer/milestone/6

**Comment by nine99systems** [comment]
Hi,
Above mentioned enhancement still not available on maven repo?

**Comment by nine99systems** [comment]
https://mvnrepository.com/artifact/net.sf.dozer/dozer/5.5.1

**Pull request merged**
