### PR TITLE
[ISSUE-800] Upgrade versions of objenesis, cglib, hibernate & lombok

### PR DESCRIPTION
**Pull request by jwyseu**
## Issue link
https://github.com/DozerMapper/dozer/issues/800

## Purpose
Upgrade versions for compatibility in updated projects

## Approach
_How does this change address the problem?_

## Open Questions and Pre-Merge TODOs
- [x] Issue created
- [ ] Unit tests pass
- [ ] Documentation updated
- [ ] Travis build passed

### CODE REVIEW

**Comment by jwyseu** [comment]
Thanks for reviewing the branch. It seems I don't have a failing test . I ran it in Intellij and then to be sure started a new maven install build. In both cases, it ran fine.
I tried as well with JDK8 and with JDK17

Anyway I run the current dozer version now in an application with objensis 3.2 (instead of the 2.6 that should be used when importing it) and it seems to work fine. But could of course be that we are not using the feature requiring objensis.

**Comment by garethahealy** [comment]
I was on JDK11, maybe thats why.

**Comment by jwyseu** [comment]
Ok I'll run the maven build with JDK11

**Comment by garethahealy** [comment]
```
[INFO] Running com.github.dozermapper.core.loader.api.FieldsMappingOptionsTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.501 s <<< FAILURE! - in com.github.dozermapper.core.loader.api.FieldsMappingOptionsTest
[ERROR] testHintAandB(com.github.dozermapper.core.loader.api.FieldsMappingOptionsTest)  Time elapsed: 0.482 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException:

Mockito cannot mock this class: class com.github.dozermapper.core.loader.DozerBuilder$FieldMappingBuilder.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : Homebrew
JVM vendor version : 11.0.15+0
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.15+0
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 12.4


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class com.github.dozermapper.core.loader.DozerBuilder$FieldMappingBuilder, interface com.github.dozermapper.core.loader.DozerBuilder$FieldBuider]
	at com.github.dozermapper.core.loader.api.FieldsMappingOptionsTest.testHintAandB(FieldsMappingOptionsTest.java:29)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class com.github.dozermapper.core.loader.DozerBuilder$FieldMappingBuilder, interface com.github.dozermapper.core.loader.DozerBuilder$FieldBuider]
	at com.github.dozermapper.core.loader.api.FieldsMappingOptionsTest.testHintAandB(FieldsMappingOptionsTest.java:29)
Caused by: java.lang.IllegalStateException:

Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
	at com.github.dozermapper.core.loader.api.FieldsMappingOptionsTest.testHintAandB(FieldsMappingOptionsTest.java:29)
Caused by: java.lang.UnsupportedOperationException: NestHost requires ASM7
	at com.github.dozermapper.core.loader.api.FieldsMappingOptionsTest.testHintAandB(FieldsMappingOptionsTest.java:29)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   FieldsMappingOptionsTest.testHintAandB:29 Mockito
Mockito cannot mock this cl...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by jwyseu** [comment]
Thank you for the stack trace. So seems it is just a mockito issue with newer Java versions, upgrading mockito fixed it (I could in the end reproduce it with a 'maven clean install' when using jdk11)

I still see some issue with the OSGI tests
```
[org.ops4j.pax.exam.junit.impl.ProbeRunner] : creating PaxExam runner for class com.github.dozermapper.osgitests.SpringKarafContainerTest
[org.ops4j.pax.exam.spi.PaxExamRuntime] : Found TestContainerFactory: org.ops4j.pax.exam.karaf.container.internal.KarafTestContainerFactory

java.lang.AssertionError: Invalid link file was provided: org.apache.commons.io.link

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at com.github.dozermapper.osgitests.support.BundleOptions.localBundle(BundleOptions.java:88)
	at com.github.dozermapper.osgitests.support.BundleOptions.coreBundles(BundleOptions.java:44)
	at com.github.dozermapper.osgitests.SpringKarafContainerTest.config(SpringKarafContainerTest.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ops4j.pax.exam.spi.reactors.ReactorManager.addConfigurationsToReactor(ReactorManager.java:248)
	at org.ops4j.pax.exam.spi.reactors.ReactorManager.prepareReactor(ReactorManager.java:184)
	at org.ops4j.pax.exam.junit.impl.ProbeRunner.<init>(ProbeRunner.java:78)
	at org.ops4j.pax.exam.junit.PaxExam.createDelegate(PaxExam.java:82)
```
Unfortunately I don't know anything about OSGI so I have no idea how to tackle those.

**Pull request merged**
