### PR TITLE
Performance - ClassMappings : The computed mapping is now added to the cache

### PR DESCRIPTION
**Pull request by gdarmont**
- This bug fix allows a major performance improvement (as expected when
  using a cache)

### CODE REVIEW

**Comment by lauriharpf** [comment]
Hi @gdarmont, thanks for the pull request!

Do you happen to have an example test that demonstrates the performance improvement after applying this change? I ran a quick, highly simplistic and non-scientific test ([http://pastebin.com/082iSukr](test source is in PasteBin)) three times with `mvn -Dtest=MappingPerformance test` :

With pull request #254 added to codebase:

    Done mapping 1000000 objects. Duration 4714 ms.
    Done mapping 1000000 objects. Duration 2623 ms.

    Done mapping 1000000 objects. Duration 4247 ms.
    Done mapping 1000000 objects. Duration 2334 ms.

    Done mapping 1000000 objects. Duration 4415 ms.
    Done mapping 1000000 objects. Duration 2400 ms.

Without pull request #254:

    Done mapping 1000000 objects. Duration 3870 ms.
    Done mapping 1000000 objects. Duration 2049 ms.

    Done mapping 1000000 objects. Duration 3736 ms.
    Done mapping 1000000 objects. Duration 2634 ms.

    Done mapping 1000000 objects. Duration 4339 ms.
    Done mapping 1000000 objects. Duration 2417 ms.

This does not show a clear performance difference, but perhaps there are other cases where the performance differs?

**Comment by garethahealy** [comment]
@gdarmont ; any update on this?

**Comment by gdarmont** [comment]
@garethahealy Sorry I forgot that PR. No update needed here to me. The PR code is used in production on our side and works very well. 

@lauriharpf didn't see any performance update, and this is perfectly normal since the proposed patch puts in cache the result of `findInterfaceMapping`. The code used to make the benchmark does not use interface mapping.

But, as always, perfomance improvements may highly depends on use case. In our case, we have a lots of mappings (1000+), mostly generated programmatically.

**Comment by garethahealy** [comment]
@gdarmont ; thanks for update.

**Pull request merged**
