### PR TITLE
Merging dozer-osgi artifact with dozer core

### PR DESCRIPTION
**Pull request by orange-buffalo**
`dozer-osgi` module is redundant. Having OSGI bundle descriptor inside core jar is harmless for non-OSGI environments. All the libraries out there that are OSGI-capable produce only one single OSGI-ready artifact. This pull request merges `dozer-osgi` into `dozer`. 

The commit just transfers the configuration from `dozer-osgi` POM into `dozer` POM, with the following exceptions:
* No embedded dependencies used. Old configuration embedded OSGI core and Felix into the bundle, which caused problems like in #224. Besides, having container implementation classes inside bundle is not required. 
* No private package configuration. Anyway bundle plugin ignored it and threw warnings into the build log.
* No import of `org.dozer.*`, as the bundle itself provides those packages. 

Next steps would be to generate bundle descriptor automatically from maven configuration instead of defining it manually. Prerequisite for this is proper organization of `optional` dependencies as OSGI is sensitive to this. 

Part of changes in #336.

### CODE REVIEW

**Comment by garethahealy** [comment]
@orange-buffalo ; minor change. Can you put the OSGi plugins under the Core ones and make them alphabetical order, with a heading of OSGi plugins, i.e.: @ https://github.com/orange-buffalo/dozer/blob/cc1ae301e87390087edddbdca70e6c21e03bc017/core/pom.xml#L244

**Comment by orange-buffalo** [comment]
@garethahealy will do, no worries. Just one question to be sure: when sorting alphabetically, should I first sort by `groupId` and then by `artifactId` or only by `artifactId`?

**Comment by garethahealy** [comment]
Group then artifactId.

**Comment by orange-buffalo** [comment]
@garethahealy, all done.

**Pull request merged**
