### PR TITLE
Issue #219

### PR DESCRIPTION
**Pull request by josejuanmontiel**
More info: https://github.com/DozerMapper/dozer/issues/219
Original reference (and test for this):
https://sourceforge.net/p/dozer/bugs/300/

### CODE REVIEW

**Comment by garethahealy** [comment]
@josejuanmontiel ; can you have a quick check at travis, its failing to compile. I would of expected a test failure.

**Comment by josejuanmontiel** [comment]
[dozer.patch.txt](https://github.com/DozerMapper/dozer/files/1074328/dozer.patch.txt)
I'm not sure my test produce this errors... but if i ignore this 3 test, its compile in my machine... give more time to review carefully :)

**Comment by josejuanmontiel** [comment]
Well i fixed "other tests" that fails to in master ;) and, now pass... one seems that error message "change", and other needs to specify directly the location of dozer.properties...

Hope this work. Remember, this came from "Option for configure ClassMap in polymorphism case #219"

**Comment by garethahealy** [comment]
@josejuanmontiel ; i think a bad rebase/merge has happened, as this PR shows changes which have came from other PRs, so its quite hard to understand what you've changed...

**Comment by josejuanmontiel** [comment]
I made and update of my fork from master... to keep update from prossible changes... you still can filter my changes in the "pull request view" filtering by my commit... https://github.com/DozerMapper/dozer/pull/433/commits/38324e385a772564de02596274a612d588cb20da tell me if do you need some else.

Thanks.

**Comment by garethahealy** [comment]
@josejuanmontiel ; I am a bit confused. I thought this PR would show a test failing. But it doesn't... what are you trying to show with this PR?

**Pull request closed without merging**
