### PR TITLE
Added draft v1 of jaxb contract first

### PR DESCRIPTION
**Pull request by garethahealy**
The idea of this is PR is as follows. Currently, there is no connection between the XSD and model used by dozer. If someone wants to add a new field to dozer, they need to change:
- xsd
- xml parser
- dozer builder api

This PR brings all of those things into one, following a JAXB contract-first method.

The new JAXB is only enabled via a system property, moving forward it would be the sole implementation, which would allow for the below package to be replaced:
- https://github.com/DozerMapper/dozer/tree/master/core/src/main/java/org/dozer/loader

Release target:
- 6.1; disabled by default, but user can opt to use by setting system var
- 6.2; enabled and old code deprecated
- 6.3; old code removed

PR is not complete, still need to do some tweaks, but thought i'd share early.

### CODE REVIEW

**Comment by garethahealy** [comment]
@orange-buffalo ; thoughts / ideas / views :)

**Comment by orange-buffalo** [comment]
@garethahealy great work! I appreciate the idea and improvements it brings. 

I would suggest to add [Project Lombok](https://projectlombok.org/features/all) to Dozer in this PR - a lot of boilerplate code will disappear and model classes will become even more readable. 

And did I get it right that in the end XSD scheme would be automatically generated by model classes?

**Comment by garethahealy** [comment]
@orange-buffalo ; yes, the XSD would be generated from the model (TODO task).

I've used lombok with standard POJO, but no JAXB POJOs, so will have a look this week and update accordingly.

Tasks to do:

- [ ] JAXB XSD generation
- [ ] Lombok
- [ ] Fix tests
- [ ] Update EL resolving to use a decorator pattern (https://sourcemaking.com/design_patterns/decorator)
- [ ] Research into creating an "API" style builder using new model
- [ ] Research into creating an "Annotation" style builder using new model

**Comment by garethahealy** [comment]
@orange-buffalo ; i tried to use lombok, but couldn't get it to work in conjunction with JAXB schemagen. Constantly got errors - schemagen isn't that helpful in the error description either, just "failed"

**Comment by orange-buffalo** [comment]
@garethahealy, I will try to check your branch to see if this problem could be resolved. If [jaxb2-maven-plugin](http://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.2/schemagen-mojo.html) is used, they claim to generate scheme "from compile-scope Java sources or *binaries*", so in case it is possible to use compiled classes, all the code should already be in place after annotation processor execution.

**Comment by garethahealy** [comment]
@orange-buffalo ; need to re-create PR, accidentally deleted it with a bad merge :)

**Pull request closed without merging**
