### PR TITLE
Added check for super type excluded fields

### PR DESCRIPTION
**Pull request by garethahealy**
Part2:
- https://github.com/DozerMapper/dozer/issues/451
- https://github.com/DozerMapper/dozer/issues/300

CC @orange-buffalo @vguna

### CODE REVIEW

**Comment by garethahealy** [comment]
@vguna have you had chance to check if this PR solves your issue?

**Comment by vguna** [comment]
Not yet, but I will this weekend. Thanks!

**Comment by vguna** [comment]
LGTM. My testcase is working with it. Not yet tested my main application - which would need a 5.5.1 -> 6.0.2 upgrade first.

But I also re-tested https://github.com/DozerMapper/dozer/pull/467/files with my provided testcase `OneWayClassMappingTest` updated to 6.0.2-SNAPSHOT (master): https://github.com/vguna/dozer-tests

It fails with ClassCastException showed below. The strange thing is: executing them isolated works :). So maybe something with mapped instance caching is broken?

```
PASSED: testDto2Entity
FAILED: testEntity2Dto
java.lang.ClassCastException: test.model.MyEntity cannot be cast to test.model.MyMinimalDto
	at test.OneWayClassMappingTest.testEntity2Dto(OneWayClassMappingTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
``´

**Comment by vguna** [comment]
Any additional info needed for this? Added the mentiond repo to travis that is built once a day and shows the build status. So should go green if the fix is working :).

**Comment by garethahealy** [comment]
@vguna ; sorry, not had enough spare time to carry on looking into this. Will try before Christmas.
- https://travis-ci.org/vguna/dozer-tests

**Comment by garethahealy** [comment]
@vguna ; just did some quick debuging. It seems the test passes when run on its own, but not as a suite. Its a bit weird, as the exact same test is on the dozer-core, and that doesn't fail.

**Comment by garethahealy** [comment]
@vguna ; have just pushed new commit. your repo builds/passes for me locally. can you please check as well.

Thinking more about this PR, i am inclined to change how i've implemented it currently, and make it optional. i.e.: use decides via a mapping flag, if super types are overridden. but at-least we have a starting point which should hopefully work for your use case.

**Comment by vguna** [comment]
Don't worry. I appreciate the time you spent on dozer, thanks!
I'll take a look and report back.

**Comment by vguna** [comment]
Hm, I fetched the latest dozer master, built it and ran my tests locally. But they failed like on travis. I'm missing something here?

**Comment by garethahealy** [comment]
@vguna ; you need to checkout this PR, and not master.

**Comment by vguna** [comment]
Ah, true :). Works for me as well!

**Pull request closed without merging**
