### PR TITLE
Added dozer-schema jar

### PR DESCRIPTION
**Pull request by garethahealy**
https://github.com/DozerMapper/dozer/issues/407

### CODE REVIEW

**Comment by garethahealy** [comment]
@orange-buffalo ; would this cause any OSGi class loader issues. I don't think so, but thought best to check.

**Comment by orange-buffalo** [comment]
@garethahealy, probably it should be okay. The schema in OSGi is resolved using `org.dozer.osgi.OSGiClassLoader`:
```java
    @Override
    public URL loadResource(String uri) {
      return context.getBundle().getResource(uri);
    }
```
As this uses "bundle's class loader", schema should be resolved as long as `schema` bundle is in dependencies of the `dozer` bundle. To be on the safe side, I would suggest to remove `@Ignore` from test `org.dozer.osgi.OsgiContainerTest#shouldLoadMappingFile`.

**Comment by garethahealy** [comment]
@orange-buffalo ; i've enabled the test and tweaked the code to better support OSGi. The code resolves the xsd via:

1. Checks if DozerClassloader (i.e.: maybe the user is using a local XSD for some reason)
2. Trys classloader for dozer-schema.jar
3. Trys bundle context for dozer-schema.jar

**Comment by orange-buffalo** [comment]
@garethahealy, looks good to me.

**Pull request merged**
