### PR TITLE
Added optional support for mapping annotation

### PR DESCRIPTION
**Pull request by psnippen**
In some cases the source or target field doesn't exists. The current implementation throws an exception in this case.
With the optional=true option before adding the annotation mapping validate that the field exists. If not the annotation is not mapped and the current exception will not occure.

### CODE REVIEW

**Comment by garethahealy** [comment]
@psnippen ; can you rebase with latest to force travis to retest

**Comment by psnippen** [comment]
@garethahealy rebase finished

**Comment by garethahealy** [comment]
@psnippen ; as you've changed the code slightly, would it not be better to just have 1 method and pass in a generic class, instead of mustMapToDest and mustMapToSrc? As both of these methods seem to do the same thing, but just call different getters.

Can you also add a unit test, for this change?

And finally, squash your commits.

**Comment by psnippen** [comment]
@garethahealy improved the code and added unittest.
Had some issues with squash. Can you validate if it is ok now?

**Comment by garethahealy** [comment]
@psnippen ; yeah, doesn't look like you've squashed. If you see the answer from this post, it should explain how to do it.

http://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed

**Comment by psnippen** [comment]
@garethahealy ok made a squash commit. Once again: can you validate if it ok now?

**Comment by garethahealy** [comment]
@psnippen ; sorry, can you rebase again. I'll merge once thats done.

**Comment by psnippen** [comment]
@garethahealy sorry been a while, but i've rebased again

**Pull request merged**
