### PR TITLE
#285 Dozer interceptor

### PR DESCRIPTION
**Pull request by ssarabun**
#285 Dozer interceptor

I've created patch, but I cannot check how it works, because dozer project is not compiled on my PC.

### CODE REVIEW

**Comment by garethahealy** [comment]
@ssarabun ; can you rebase with latest to force travis to retest

**Comment by ssarabun** [comment]
How can I do it? Do I need to new pull request?

**Comment by garethahealy** [comment]
@ssarabun ; https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by ssarabun** [comment]
@garethahealy thank you for your help, I have some problem with java 8. There are a lot of projects that use  java 7, and to increase version, it is not good idea.

I've checked, dozer will be compiled with java 7 too, can I decrease version and commit changes?

**Comment by ssarabun** [comment]
It is very bad for me, because I work with JEE7 and I cannot change stack. If dozer works with JDK 8 and more, a lot of developers will have to refuse from dozer. And I think that enterprise projects are main users of dozer.

**Comment by garethahealy** [comment]
JEE7 can be run on JDK8 and would expect all JEE7 application containers to support JDK8 now, for example, JBoss EAP supports JDK8.

**Comment by ssarabun** [comment]
JBoss EAP works, but some extensions for JBossEAP not work.

**Comment by garethahealy** [comment]
@ssarabun ; just trying to understand what this PR is trying to do. Looking at the code, it seems you want to decide whether or not to write the destination value. That logic is already here:
- https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/MappingProcessor.java#L954-L969

Is there another condition you want to check that isn't already supported?

**Comment by ssarabun** [comment]
Hi @garethahealy 
Which decision do you make?
Will you apply current pull request?
How about JDK7?

**Comment by garethahealy** [comment]
@ssarabun ; I dont like the idea of passing in MapperInterceptor to the mapper, which is then passed through several method calls. It feels like there is a better solution which works via the events mechanism.

**Comment by ssarabun** [comment]
@garethahealy 
> I dont like the idea of passing in MapperInterceptor to the mapper, which is then passed through several method calls.

Yes, I think so

> It feels like there is a better solution which works via the events mechanism.

Could you provide additional info about that?

**Comment by garethahealy** [comment]
Closing for time being, as PR direction is not the best. Needs further investigation to solve problem in a better way.

**Pull request closed without merging**
