### PR TITLE
Update CustomGetSetPropertyDescriptor.java

### PR DESCRIPTION
**Pull request by mjunginger**
Issue #263

### CODE REVIEW

**Comment by mjunginger** [comment]
Art there any concerns against pulling that?

**Comment by garethahealy** [comment]
@mjunginger ; what is this PR trying to solve? The cold looks very similar but just with a ternary operation and formatting changed.

**Comment by garethahealy** [comment]
@mjunginger any update?

**Comment by garethahealy** [comment]
Closing due to inactivity.

**Pull request closed without merging**
