### PR TITLE
Polishing code on dozer-spring-boot-autoconfigure

### PR DESCRIPTION
**Pull request by kazuki43zoo**
## Purpose
I've polished some codes on dozer-spring-boot-autoconfigure.

* Remove `@Autowired` from constructor

## Open Questions and Pre-Merge TODOs
- [ ] Issue created
- [x] Unit tests pass
- [ ] Documentation updated
- [x] Travis build passed

### CODE REVIEW

**Comment by garethahealy** [comment]
@kazuki43zoo ; but why have you removed it? if its not needed, please explain why.

**Comment by kazuki43zoo** [comment]
Since Spring 4.3+ (Spring Boot 1.4+) , It is no longer necessary to specify the `@Autowired` annotation if the target bean only defines one constructor.
As actually, AutoConfiguration classes provided by Spring Boot uses constructor injection without `@Autowired`

* https://github.com/spring-projects/spring-boot/commit/5009933788f5f8c687719de6a697074ff80b1b69

* https://github.com/spring-projects/spring-boot/commit/19d8c5e6f649987a54f4d1834de57b6dfb18b969

* https://docs.spring.io/spring/docs/4.3.18.RELEASE/spring-framework-reference/htmlsingle/#v4_3-Core-Container-Improvements.

WDYT?

**Comment by garethahealy** [comment]
@kazuki43zoo ; OK. The dozer bits are not strictly tied to a spring4 version, so if the end user wanted to use spring 4.0.0, they could. We only test the bits against the latest spring4 version.

So with that in mind, i'd prefer not to change this.

**Comment by garethahealy** [comment]
@kazuki43zoo ; fair comment.

**Pull request merged**
