### PR TITLE
[640] Added set to set conversation

### PR DESCRIPTION
**Pull request by garethahealy**
https://github.com/DozerMapper/dozer/issues/640

### CODE REVIEW

**Comment by garethahealy** [comment]
@dmni1905 ; can you test this fixes your issue please

**Comment by dmni1905** [comment]
I update dozer version to 6.2.0 and add you fix
https://github.com/dmni1905/DozerMapperTest/blob/master/src/test/java/DozerMapTest.java

BUT:
```
java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.List

	at org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:610)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:472)
	at org.dozer.MappingProcessor.mapMap(MappingProcessor.java:640)
	at org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:428)
	at org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:375)
	at org.dozer.MappingProcessor.mapField(MappingProcessor.java:325)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:285)
	at org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:234)
	at org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:208)
	at org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:182)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:115)
	at org.dozer.MappingProcessor.map(MappingProcessor.java:110)
	at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:141)
	at DozerMapTest.test(DozerMapTest.java:54)
```
screenshot_5

**Comment by dmni1905** [comment]
@garethahealy, are you check?

**Comment by garethahealy** [comment]
@dmni1905 ; have been busy recently. will try and look at it again soon.

**Comment by angelocorreia** [comment]
Was this fix released? I still see this bug in 6.4.0

**Comment by garethahealy** [comment]
@angelocorreia ; sadly not. i've not had much time recently to look at this. if you are willing to help, that would be great.

**Comment by dmni1905** [comment]
Hi, I updated tests. pls, using new link for this error: https://github.com/dmni1905/DozerMapperTest/blob/master/src/test/java/main/MapMappingTest.java

**Comment by dmni1905** [comment]
@garethahealy was this fix resolved?

**Pull request closed without merging**
