### PR TITLE
OSGI bundle improvements

### PR DESCRIPTION
**Pull request by orange-buffalo**
This pull request is to improve OSGI bundle (change ported from https://github.com/crxmarkets/dozer).

The problems that were solved here:
* `dozer-osgi` bundle contains OSGI API and Felix implementation classes. Although they are not exported, it is still not the best idea to include framework classes into the assembly. This may cause problems in non-OSGI environment, for instance, we faced classpath conflicts in Camel Blueprint tests. 
Resolution: bundle only Dozer project binaries. 

*  `dozer-osgi` module is redundant. Having OSGI bundle descriptor inside core jar is harmless for non-OSGI environments. All the libraries out there that are OSGI-capable produce only one  single OSGI-ready artifact. 
Resolution: merged `dozer-osgi` into `dozer` module, making `dozer` OSGI-capable.

* OSGI Version 4.3.0 is too old.
Resolution: upgraded to OSGI 5.0.0 which is more common nowadays (although not the latest one). 

* Aether resolver used in OSGI tests has some significant drawbacks, where the main one is that it is not using Maven reactor configuration but its own implementation of artifacts resolution. As a result `package` on clean system will not work + artifacts used to compile the code could be different from those resolved by Aether. For more details see http://veithen.github.io/alta/examples/pax-exam.html.
Resolution: replaced with alternative approach which relies on Maven reactor resolution. 
In addition, updated some other OSGI-test dependencies here.

* Manual configuration of Maven Bundle Plugin is an overhead and source of potential error whenever project dependencies / package structure changes. 
Resolution: make plugin produce bundle descriptor based on Maven artifact configuration.

During implementation it was discovered that some dependencies in core module are redundant and never used - removed them. Some others are in fact optional, as they are used only when specific functionality is explicitly enabled by user. As this is extremely important in OSGI world, updated those dependencies to optional.

### CODE REVIEW

**Comment by garethahealy** [comment]
@orange-buffalo ; can you rebase as i did a change a few days ago which conflicts/overlaps with some of your changes.

Can you also split this PR into several, i.e.:

1. Merging of dozer and dozer-osgi.
2. upgrade osgi to v5 and pax-exam.
3. updating of the maven bundle plugin.
4. removing un-needed deps.

Am happy with 1/2 but unsure about 3/4, so need to just validate when PRs are raised.

**Comment by orange-buffalo** [comment]
@garethahealy, everything but upgrading osgi/pax-exam is quite coupled together and not that trivial to split into different pull requests.  I'll try to find out the best way to do that.

**Comment by garethahealy** [comment]
Anything else related that needs to be raised? or can this now be closed?

**Comment by orange-buffalo** [comment]
One more thing left - to move away from manual configuration of OSGi bundle descriptor and use automatic descriptor generation based on Maven artifact configuration. This requires careful handling of optional dependencies. I believe most of them are already handled, but need to double check this. I will prepare the last pull request soon and then close the initial one.

**Comment by orange-buffalo** [comment]
Closing this pull request as the last point has been addressed in #353.

**Pull request closed without merging**
